### **1. Sinh viên cho ví vụ về phép cộng, trừ hai ma trận numpy.**


In [ ]:
# Câu 1
import numpy as np
a = np.array([-8, 15])
X = np.array([[1, 5],
 [3, 4],
 [2, 3]])

y = np.add(X, a)
print("X + a = ")
print(y)

y = np.subtract(X, a)
print("X - a = ")
print(y)

X + a = 
[[-7 20]
 [-5 19]
 [-6 18]]
X - a = 
[[  9 -10]
 [ 11 -11]
 [ 10 -12]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### **2. Sinh viên sử dụng pandas xử lý các yêu cầu sau:**
- Đọc CSV thành Dataframe và hiển thị
- Hãy chuyển index mặc định thành giá trị cột id
- Sắp xếp dữ liễu theo nhiều cột (sort)
- Chọn một cột cụ thể và hiển thị nó
- Chọn 2 hàng đầu tiền và hiển thị chúng
- Hãy chọ một hàng dựa trên một điều kiện giá trị của cột
- Thay đổi một vài giá trị thành NaN ở CSV, sau đó đọc lên thành Dataframe và
thay thế chúng bằng giá trị 0
- Ở cột Z chuyển giá trị lớn hơn 90 là True và nhỏ hơn là False trong Dataframe
- Chuyển Dataframe trên thành 2 Dataframe d1 và d2; d1 chứ cột X và Y, d2
chứa cột Z; cuối cùng d3 là thành quả của nối 2 Dataframe d1 và d2
- Dùng tính năng thống kê hãy hiển thị kết quả thông kể các giá trị thuộc tính
của Dataframe



In [ ]:
# Câu 2
import pandas as pd

print('Đọc CSV thành Dataframe và hiển thị')
df = pd.read_csv('/content/BT2.csv')
print(df, '\n')

print('Chuyển index mặc định thành giá trị cột id')
df.set_index('Unnamed: 0', inplace = True)
print(df, '\n')

print('Sắp xếp dữ liệu theo nhiều cột (sort)')
df_sorted = df.sort_values(by = ['X', 'Y', 'Z'])
print(df_sorted, '\n')

print('Chọn một cột cụ thể và hiển thị nó')
print(df['X'], '\n')

print('Chọn 2 hàng đầu tiền và hiển thị chúng')
print(df.head(2), '\n')

print('Hãy chọ một hàng dựa trên một điều kiện giá trị của cột')
print('Chọn hàng mà X có giá trị bằng 85')
df_selectrow = df.loc[df['X'] == 85]
print(df_selectrow, '\n')

print('Thay đổi một vài giá trị thành NaN ở CSV, sau đó đọc lên thành Dataframe và thay thế chúng bằng giá trị 0')
other_df = pd.read_csv('/content/BT2.1.csv')
print('Dataframe trước khi thay đổi')
print(other_df, '\n')
print('Dataframe sau khi thay đổi')
other_df.fillna(0, inplace = True)
print(other_df, '\n')

print('Ở cột Z chuyển giá trị lớn hơn 90 là True và nhỏ hơn là False trong Dataframe')
def greater_than_90(x):
    if x > 90:
        return True
    else:
        return False
df['Z'] = df['Z'].apply(greater_than_90)
print(df, '\n')

print('Chuyển Dataframe trên thành 2 Dataframe d1 và d2; d1 chứ cột X và Y, d2 chứa cột Z; cuối cùng d3 là thành quả của nối 2 Dataframe d1 và d2')
print('Dataframe d1')
d1 = df.drop(columns = ['Z'])
print(d1)
print('Dataframe d2')
d2 = df[['Z']]
print(d2)
print('Dataframe d3')
d3 = pd.concat([d1, d2], axis = 1)
print(d3, '\n')

print('Dùng tính năng thống kê hãy hiển thị kết quả thông kê các giá trị thuộc tính của Dataframe')
print(other_df.describe())

Đọc CSV thành Dataframe và hiển thị
   Unnamed: 0   X   Y   Z
0           1  78  84  86
1           2  85  94  97
2           3  80  83  73
3           4  96  94  96
4           5  86  86  83 

Chuyển index mặc định thành giá trị cột id
             X   Y   Z
Unnamed: 0            
1           78  84  86
2           85  94  97
3           80  83  73
4           96  94  96
5           86  86  83 

Sắp xếp dữ liệu theo nhiều cột (sort)
             X   Y   Z
Unnamed: 0            
1           78  84  86
3           80  83  73
2           85  94  97
5           86  86  83
4           96  94  96 

Chọn một cột cụ thể và hiển thị nó
Unnamed: 0
1    78
2    85
3    80
4    96
5    86
Name: X, dtype: int64 

Chọn 2 hàng đầu tiền và hiển thị chúng
             X   Y   Z
Unnamed: 0            
1           78  84  86
2           85  94  97 

Hãy chọ một hàng dựa trên một điều kiện giá trị của cột
Chọn hàng mà X có giá trị bằng 85
             X   Y   Z
Unnamed: 0            
2           85  94  

### **3. Sinh viên tự tìm hiểu thực hiện lại ví dụ dùng mô hình Linear Regression trong thư viện scikit-learning bằng các thư viện sau:**
**- TensorFlow**

**- Keras**

**- PyTorch**

- Scikit-learning

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
# X is a matrix that represents the training dataset
# y is a vector of weights, to be associated with input dataset
X = np.array([[3], [5], [7], [9], [11]]).reshape(-1, 1)
y = [8.0, 9.1, 10.3, 11.4, 12.6]
lreg_model = LinearRegression()
lreg_model.fit(X, y)
# New data (unseen before)
new_data = np.array([[13]])
print('Model Prediction for new data: $%.2f' %
lreg_model.predict(new_data)[0] )

Model Prediction for new data: $13.73


- TensorFlow

In [ ]:
#Câu 3: Tensorflow
import tensorflow as tf

class SimpleLinearRegression:
  def __init__(self, initializer='random'):
    if initializer=='ones':
      self.var = 1.
    elif initializer=='zeros':
      self.var = 0.
    elif initializer=='random':
      self.var = tf.random.uniform(shape=[], minval=0., maxval=1.)

    self.m = tf.Variable(1., shape=tf.TensorShape(None))
    self.b = tf.Variable(self.var)

  def predict(self, x):
    return tf.reduce_sum(self.m * x, 1) + self.b

  def mse(self, true, predicted):
    return tf.reduce_mean(tf.square(true-predicted))

  def update(self, X, y, learning_rate):
    with tf.GradientTape(persistent=True) as g:
      loss = self.mse(y, self.predict(X))

    print("Loss: ", loss)
    dy_dm = g.gradient(loss, self.m)
    dy_db = g.gradient(loss, self.b)

    self.m.assign_sub(learning_rate * dy_dm)
    self.b.assign_sub(learning_rate * dy_db)

  def train(self, X, y, learning_rate=0.01, epochs=5):
    if len(X.shape)==1:
      X=tf.reshape(X,[X.shape[0],1])

    self.m.assign([self.var]*X.shape[-1])
    for i in range(epochs):
      print("Epoch: ", i)

      self.update(X, y, learning_rate)

# Tạo dữ liệu mẫu
x = np.array([[3], [5], [7], [9], [11]]).reshape(-1, 1)
y = np.array([8.0, 9.1, 10.3, 11.4, 12.6])

# Tính các thông số tối ưu cho mô hình
mean_label = y.mean(axis=0)
std_label = y.std(axis=0)
mean_feat = x.mean(axis=0)
std_feat = x.std(axis=0)
x = (x-mean_feat)/std_feat
y = (y-mean_label)/std_label

# Tạo model và các thông số cần thiết
linear_model = SimpleLinearRegression('zeros')

#Huấn luyện model
linear_model.train(x, y, learning_rate = 0.01, epochs = 500)

# Dự đoán giá trị cho dữ liệu mới
x_test = [[13]]

# standardize
x_test = (x_test-mean_feat)/std_feat
# reverse standardization
pred = linear_model.predict(x_test)
pred *= std_label
pred += mean_label

print('Model Prediction for new data: $%.2f' %pred)

Epoch:  0
Loss:  tf.Tensor(1.0, shape=(), dtype=float32)
Epoch:  1
Loss:  tf.Tensor(0.960409, shape=(), dtype=float32)
Epoch:  2
Loss:  tf.Tensor(0.9223857, shape=(), dtype=float32)
Epoch:  3
Loss:  tf.Tensor(0.88586825, shape=(), dtype=float32)
Epoch:  4
Loss:  tf.Tensor(0.8507969, shape=(), dtype=float32)
Epoch:  5
Loss:  tf.Tensor(0.81711435, shape=(), dtype=float32)
Epoch:  6
Loss:  tf.Tensor(0.78476554, shape=(), dtype=float32)
Epoch:  7
Loss:  tf.Tensor(0.7536978, shape=(), dtype=float32)
Epoch:  8
Loss:  tf.Tensor(0.7238604, shape=(), dtype=float32)
Epoch:  9
Loss:  tf.Tensor(0.69520444, shape=(), dtype=float32)
Epoch:  10
Loss:  tf.Tensor(0.66768336, shape=(), dtype=float32)
Epoch:  11
Loss:  tf.Tensor(0.64125216, shape=(), dtype=float32)
Epoch:  12
Loss:  tf.Tensor(0.61586744, shape=(), dtype=float32)
Epoch:  13
Loss:  tf.Tensor(0.5914881, shape=(), dtype=float32)
Epoch:  14
Loss:  tf.Tensor(0.56807417, shape=(), dtype=float32)
Epoch:  15
Loss:  tf.Tensor(0.5455874, shape=(), 

- Keras

In [ ]:
# Câu 3: Keras
import tensorflow as tf
import numpy as np

# Tạo dữ liệu mẫu
X_train = np.array([[3], [5], [7], [9], [11]], dtype=np.float32)
y_train = np.array([8.0, 9.1, 10.3, 11.4, 12.6], dtype=np.float32)

# Tạo model
model = tf.keras.Sequential([tf.keras.layers.Dense(units=1, input_shape=[1])])

# Compile model với loss function và optimizer
model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(learning_rate=0.1))

# Huấn luyện model
model.fit(X_train, y_train, epochs=500, verbose=0)

# Dự đoán giá trị cho dữ liệu mới
new_data = np.array([[13]], dtype=np.float32)
prediction = model.predict(new_data)[0][0]
print('Model Prediction for new data: $%.2f' % prediction)

1/1 [==============================] - 0s 42ms/step
Model Prediction for new data: $13.73


Model Prediction for new data: $10.51


- PyTorch

In [ ]:
#Câu 3: Pytorch
import torch
from torch.autograd import Variable

x_data = Variable(torch.Tensor([[3], [5], [7], [9], [11]]))
y_data = Variable(torch.Tensor([[8.0], [9.1], [10.3], [11.4], [12.6]]))


class LinearRegressionModel(torch.nn.Module):

	def __init__(self):
		super(LinearRegressionModel, self).__init__()
		self.linear = torch.nn.Linear(1, 1) # One in and one out

	def forward(self, x):
		y_pred = self.linear(x)
		return y_pred

# our model
our_model = LinearRegressionModel()

criterion = torch.nn.MSELoss(size_average = False)
optimizer = torch.optim.Adam(our_model.parameters(), lr = 0.01)

for epoch in range(5000):

	# Forward pass: Compute predicted y by passing
	# x to the model
	pred_y = our_model(x_data)

	# Compute and print loss
	loss = criterion(pred_y, y_data)

	# Zero gradients, perform a backward pass,
	# and update the weights.
	optimizer.zero_grad()
	loss.backward()
	optimizer.step()
	print('epoch {}, loss {}'.format(epoch, loss.item()))

new_var = Variable(torch.Tensor([[13.0]]))
pred_y = our_model(new_var)
print('Model Prediction for new data: $%.2f' %our_model(new_var).item())


/usr/local/lib/python3.10/dist-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
epoch 1, loss 888.2548217773438
epoch 2, loss 877.044921875
epoch 3, loss 865.91015625
epoch 4, loss 854.851806640625
epoch 5, loss 843.8709716796875
epoch 6, loss 832.9689331054688
epoch 7, loss 822.1466674804688
epoch 8, loss 811.4052124023438
epoch 9, loss 800.7457275390625
epoch 10, loss 790.169189453125
epoch 11, loss 779.6765747070312
epoch 12, loss 769.2686767578125
epoch 13, loss 758.9462890625
epoch 14, loss 748.71044921875
epoch 15, loss 738.5616455078125
epoch 16, loss 728.5006713867188
epoch 17, loss 718.5283203125
epoch 18, loss 708.6448364257812
epoch 19, loss 698.85107421875
epoch 20, loss 689.1473388671875
epoch 21, loss 679.5341796875
epoch 22, loss 670.011962890625
epoch 23, loss 660.5809326171875
epoch 24, loss 651.2413940429688
epoch 25, loss 641.99365234375
epoch 26, loss 632.8378295898438
epoch 27, loss 623.7741088867188
epoch 28, loss 614.8026123046875
epoch 29, loss 605.9232177734375
epoch 30, loss 597.136

### **4. Sinh viên hoàn thành code phát hiện spam với SVMs và Linear regression**

- SVM

In [ ]:
#Câu 4: SVM
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
from google.colab import drive

#Load dataset từ drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/PPHM/sms_spam_svm.csv')

#Tiền xử lí dataset
y = df.iloc[:, 0].values
y = np.where(y == 'spam', -1, 1)
X = df.iloc[:, [1, 2]].values

#Tách thành 2 phần: traning và testing với tỉ lệ 7:3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#Khởi tạo mô hình và huấn luyện
svm = SVC(kernel='linear', C=1.0, random_state=0)
svm.fit(X_train, y_train)

#Kiểm tra mô hình trên tập X_test và tính accuracy
y_pred = svm.predict(X_test)

print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Mounted at /content/drive
Misclassified samples: 7
Accuracy: 0.84


- Linear Regression

In [ ]:
#Câu 4: Linear Regression
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score

from google.colab import drive

#Load dataset từ drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/PPHM/sms_spam_svm.csv')

#Tiền xử lí dataset
y = df.iloc[:, 0].values
y = np.where(y == 'spam', -1, 1)
X = df.iloc[:, [1, 2]].values

#Tách thành 2 phần: traning và testing với tỉ lệ 7:3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#Khởi tạo mô hình và huấn luyện
model = LinearRegression()
model.fit(X_train, y_train)

#Kiểm tra mô hình trên tập X_test và tính accuracy
y_pred = model.predict(X_test)

print('Misclassified samples: %d' % (y_test != y_pred).sum())

Mounted at /content/drive
Misclassified samples: 45


### **5. Sinh viên cho biết chức năng của phương thức genfromtxt() trong thư viện numpy**

In [ ]:
# Câu 5
import pandas as pd
import numpy as np
from sklearn import *
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
phishing_dataset = np.genfromtxt('/content/phishing_dataset.csv', delimiter=',', dtype=np.int32)
print(phishing_dataset)
samples = phishing_dataset[:,:-1]
targets = phishing_dataset[:, -1]
from sklearn.model_selection import train_test_split
training_samples, testing_samples, training_targets, testing_targets = train_test_split(
 samples, targets, test_size=0.2, random_state=0)
log_classifier = LogisticRegression()
log_classifier.fit(training_samples, training_targets)
predictions = log_classifier.predict(testing_samples)
accuracy = 100.0 * accuracy_score(testing_targets, predictions)
print ("Logistic Regression accuracy: " + str(accuracy))

[[-1  1  1 ...  1 -1 -1]
 [ 1  1  1 ...  1  1 -1]
 [ 1  0  1 ...  0 -1 -1]
 ...
 [ 1 -1  1 ...  0  1 -1]
 [-1 -1  1 ...  1  1 -1]
 [-1 -1  1 ...  1 -1 -1]]
Logistic Regression accuracy: 91.67797376752601


### **6. Sinh viên hoàn thiện code Decision trees trên và đánh giá kết quả nhận được so với phương pháp Logistic regression.**

In [ ]:
#Câu 6
import pandas as pd
import numpy as np
from sklearn import *
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

phishing_dataset = np.genfromtxt('/content/phishing_dataset.csv', delimiter=',', dtype=np.int32)
samples = phishing_dataset[:,:-1]
targets = phishing_dataset[:, -1]
print('Phishing dataset')
print(phishing_dataset, '\n')

training_samples, testing_samples, training_targets, testing_targets = train_test_split(samples, targets, test_size=0.2, random_state=0)

# Tạo và huấn luyện mô hình Decision Tree
tree_classifier = tree.DecisionTreeClassifier()
tree_classifier.fit(training_samples, training_targets)

# Dự đoán trên tập kiểm tra
tree_predictions = tree_classifier.predict(testing_samples)

# Đánh giá kết quả sử dụng độ chính xác
tree_accuracy = 100.0 * accuracy_score(testing_targets, tree_predictions)
print("Decision Tree accuracy:", tree_accuracy)

Phishing dataset
[[-1  1  1 ...  1 -1 -1]
 [ 1  1  1 ...  1  1 -1]
 [ 1  0  1 ...  0 -1 -1]
 ...
 [ 1 -1  1 ...  0  1 -1]
 [-1 -1  1 ...  1  1 -1]
 [-1 -1  1 ...  1 -1 -1]] 

Decision Tree accuracy: 96.47218453188603


### **7. Sinh viên thực hiện code phát hiện phising website bằng mô hình học máy**
### **Logistic regression và Decision trees với train và test trên tập dữ liệu**
### **https://www.kaggle.com/shashwatwork/phishing-dataset-for-machinelearning**

- Logistic Regression

In [ ]:
#Câu 7: Logistic Regression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

#Load dataset từ drive
df = pd.read_csv("/content/drive/MyDrive/PPHM/Phishing_Legitimate_full.csv")

#Tiền xử lí dataset
samples = df.iloc[:, :-1]
targets = df.iloc[:, -1]

#Tách thành 2 phần: traning và testing với tỉ lệ 7:3
X_train, X_test, y_train, y_test = train_test_split(samples, targets, test_size=0.2, random_state=42)

# Tạo và huấn luyện mô hình Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)

#Kiểm tra mô hình trên tập X_test và tính accuracy
lr_preds = lr.predict(X_test)

accuracy_lr = 100.0 * accuracy_score(y_test, lr_preds)
print('Logistic Regression accuracy:' + str(accuracy_lr))

Logistic Regression accuracy:97.39999999999999


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


- Decision tree

In [ ]:
#Câu 7: Decision Tree

# Tạo và huấn luyện mô hình Logistic Regression
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

#Kiểm tra mô hình trên tập X_test và tính accuracy
dt_preds = dt.predict(X_test)

accuracy_dt = 100.0 * accuracy_score(y_test, dt_preds)
print('Decision Tree accuracy:' + str(accuracy_dt))

Decision Tree accuracy:100.0


### **8. Sinh viên thực hiện code phát hiện phising website bằng mô hình học máy Logistic regression hoặc Decision trees với train và test trên tập dữ liệu phishtank. Tham khảo cách xử lý và trích xuất thuộc tích https://github.com/surajr/URL-Classification**

In [12]:
!pip install tldextract

In [27]:
# Câu 8
import pandas as pd
import numpy as np
from urllib.parse import urlparse
import tldextract
# Trích xuất dữ liệu
URLphising = pd.read_csv('/content/verified_online.csv')
URLphising.sample().reset_index(drop=True)
URLphising.head()

phish_id                                                url  \
0   8499381               https://zb912.app.link/e/z1GDWPu15Hb   
1   8499371               https://att-login810.weeblysite.com/   
2   8499370                http://att-login810.weeblysite.com/   
3   8499369  https://www.declaratia-de-valoare.ro/chdashb/r...   
4   8499368       https://dev-arprovncia-home.pantheonsite.io/   

                                    phish_detail_url  \
0  http://www.phishtank.com/phish_detail.php?phis...   
1  http://www.phishtank.com/phish_detail.php?phis...   
2  http://www.phishtank.com/phish_detail.php?phis...   
3  http://www.phishtank.com/phish_detail.php?phis...   
4  http://www.phishtank.com/phish_detail.php?phis...   

             submission_time verified          verification_time online target  
0  2024-03-19T16:09:39+00:00      yes  2024-03-19T16:13:05+00:00    yes  Other  
1  2024-03-19T16:01:56+00:00      yes  2024-03-19T16:13:05+00:00    yes  Other  
2  2024-03-19T16:01:55+00:00      yes  2024-03-19T16:13:05+00:00    yes  Other  
3  2024-03-19T16:00:58+00:00      yes  2024-03-19T16:13:05+00:00    yes  Other  
4  2024-03-19T16:00:24+00:00      yes  2024-03-19T16:13:05+00:00    yes  Other

In [14]:
URLphising['target'].value_counts()

Other                              50249
Microsoft                            692
Internal Revenue Service             512
Facebook                             507
Apple                                485
                                   ...  
Discover Bank                          1
Bank of the West                       1
Banco Bilbao Vizcaya Argentaria        1
Binance                                1
EPPICard                               1
Name: target, Length: 111, dtype: int64

In [15]:
URLphising_extract = URLphising[['url']]
URLphising_extract['isPhising'] = 1
URLphising_extract.head()

<ipython-input-15-df12b197a60d>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  URLphising_extract['isPhising'] = 1


url  isPhising
0               https://zb912.app.link/e/z1GDWPu15Hb          1
1               https://att-login810.weeblysite.com/          1
2                http://att-login810.weeblysite.com/          1
3  https://www.declaratia-de-valoare.ro/chdashb/r...          1
4       https://dev-arprovncia-home.pantheonsite.io/          1

In [16]:
URLbenign = pd.read_csv('/content/1.Benign_list_big_final.csv')
URLbenign.columns = ['url']
URLbenign['isPhising'] = 0
URLbenign.head()

url  isPhising
0  http://1337x.to/torrent/1110018/Blackhat-2015-...          0
1  http://1337x.to/torrent/1122940/Blackhat-2015-...          0
2  http://1337x.to/torrent/1124395/Fast-and-Furio...          0
3  http://1337x.to/torrent/1145504/Avengers-Age-o...          0
4  http://1337x.to/torrent/1160078/Avengers-age-o...          0

In [17]:
URLdataset_phising = URLphising_extract.sample(n = 1000)
URLdataset_benign = URLbenign.sample(n = 1000)
URLdataset = pd.concat([URLdataset_phising, URLdataset_benign])

In [18]:
Suspicious_TLD=['zip','cricket','link','work','party','gq','kim','country','science','tk']
Suspicious_Domain=['luckytime.co.kr','mattfoll.eu.interia.pl','trafficholder.com','dl.baixaki.com.br','bembed.redtube.comr','tags.expo9.exponential.com','deepspacer.com','funad.co.kr','trafficconverter.biz']

def countdots(url):
    return url.count('.')

def countdelim(url):
    count = 0
    delim=[';','_','?','=','&']
    for each in url:
        if each in delim:
            count = count + 1

    return count


def countdelim(url):
    count = 0
    delim=[';','_','?','=','&']
    for each in url:
        if each in delim:
            count = count + 1

    return count


import ipaddress as ip

def isip(uri):
    try:
        if ip.ip_address(uri):
            return 1
    except:
        return 0


def isPresentHyphen(url):
    return url.count('-')


def isPresentAt(url):
    return url.count('@')


def isPresentDSlash(url):
    return url.count('//')


def countSubDir(url):
    return url.count('/')


def get_ext(url):
    """Return the filename extension from url, or ''."""

    root, ext = splitext(url)
    return ext


def countSubDomain(subdomain):
    if not subdomain:
        return 0
    else:
        return len(subdomain.split('.'))


def countQueries(query):
    if not query:
        return 0
    else:
        return len(query.split('&'))

In [28]:
featureSet = pd.DataFrame(columns=('url','no of dots','presence of hyphen','len of url','presence of at','presence of double slash','no of subdir','no of subdomain','len of domain','no of queries','is IP','presence of Suspicious_TLD','presence of suspicious domain','label'), dtype=np.int32)
featureSet

Empty DataFrame
Columns: [url, no of dots, presence of hyphen, len of url, presence of at, presence of double slash, no of subdir, no of subdomain, len of domain, no of queries, is IP, presence of Suspicious_TLD, presence of suspicious domain, label]
Index: []

In [29]:


def getFeatures(url, label):
    result = []
    url = str(url)

    result.append(url)
    path = urlparse(url)
    ext = tldextract.extract(url)
    result.append(countdots(ext.subdomain))
    result.append(isPresentHyphen(path.netloc))
    result.append(len(url))
    result.append(isPresentAt(path.netloc))
    result.append(isPresentDSlash(path.path))
    result.append(countSubDir(path.path))
    result.append(countSubDomain(ext.subdomain))
    result.append(len(path.netloc))
    result.append(len(path.query))
    result.append(isip(ext.domain))
    result.append(1 if ext.suffix in Suspicious_TLD else 0)
    result.append(1 if '.'.join(ext.domain) in Suspicious_Domain else 0 )
    result.append(label)
    return result

In [32]:
URLdataset["isPhising"][0:1].values[0]

URLdataset["url"][0:1]

features = getFeatures(URLdataset["url"][0:1], URLdataset["isPhising"][0:1].values)
len(features)

for i in range(len(URLdataset)):
    features = getFeatures(URLdataset["url"][i:i+1], URLdataset["isPhising"][i:i+1].values[0])
    featureSet.loc[i] = features
featureSet

url  no of dots  \
0     54133    http://www.im-creator.com/free/lobby0...           0   
1     37581    https://cf-ipfs.com/ipfs/QmdhbvvP9AgQ...           0   
2     18080    https://usp.usspvh.top/\nName: url, d...           0   
3     20896    https://l-universite-validez-votre-co...           0   
4     19974    https://biiigpond.weebly.com/\nName: ...           0   
...                                                 ...         ...   
1995  11483    http://sfglobe.com/2015/05/12/michiga...           0   
1996  26013    https://uproxx.com/tv/2015/05/whats-o...           0   
1997  11420    http://plarium.com/en/strategy-games/...           0   
1998  4578    http://distractify.com/post/related/id...           0   
1999  3319    http://correios.com.br/Para-governo/de...           0   

      presence of hyphen  len of url  presence of at  \
0                      0          81               0   
1                      0          83               0   
2                      0          57               0   
3                      0          83               0   
4                      0          63               0   
...                  ...         ...             ...   
1995                   0          83               0   
1996                   0          83               0   
1997                   0          83               0   
1998                   0          82               0   
1999                   0          82               0   

      presence of double slash  no of subdir  no of subdomain  len of domain  \
0                            1             5                0              0   
1                            1             4                0              0   
2                            1             3                0              0   
3                            1             2                0              0   
4                            1             3                0              0   
...                        ...           ...              ...            ...   
1995                         1             6                0              0   
1996                         1             6                0              0   
1997                         1             5                0              0   
1998                         1             6                0              0   
1999                         1             4                0              0   

      no of queries  is IP  presence of Suspicious_TLD  \
0                 0      0                           0   
1                 0      0                           0   
2                 0      0                           0   
3                 0      0                           0   
4                 0      0                           0   
...             ...    ...                         ...   
1995              0      0                           0   
1996              0      0                           0   
1997              0      0                           0   
1998              0      0                           0   
1999              0      0                           0   

      presence of suspicious domain  label  
0                                 0      1  
1                                 0      1  
2                                 0      1  
3                                 0      1  
4                                 0      1  
...                             ...    ...  
1995                              0      0  
1996                              0      0  
1997                              0      0  
1998                              0      0  
1999                              0      0  

[2000 rows x 14 columns]

In [33]:
sample_pt = featureSet.loc[:, 'no of dots': 'presence of suspicious domain']
target_pt = featureSet.iloc[:, [-1]]
from sklearn.model_selection import train_test_split
sample_train_pt, sample_test_pt, target_train_pt, target_test_pt = train_test_split(sample_pt, target_pt, test_size=0.3, random_state=0)
from sklearn import tree
tree_model_pt = tree.DecisionTreeClassifier()


tree_model_pt.fit(sample_train_pt, target_train_pt)
prediction_pt = tree_model_pt.predict(sample_test_pt)
from sklearn.metrics import accuracy_score
accuracy = 100 * accuracy_score(target_test_pt, prediction_pt)
print("Decision Tree applied on PhisTank Dataset has the accuracy score: %s" % str(accuracy))


Decision Tree applied on PhisTank Dataset has the accuracy score: 79.33333333333333
